name: Build API

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Timestamp
        run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGE_TOKEN }}

      - name: Build and tag image
        run: |
          docker build . --tag ghcr.io/kitscode/big-event-api:$TIMESTAMP
          docker tag ghcr.io/kitscode/big-event-api:$TIMESTAMP ghcr.io/kitscode/big-event-api:latest

      - name: Push image to GitHub Container Registry
        run: |
          docker push ghcr.io/kitscode/big-event-api:$TIMESTAMP
          docker push ghcr.io/kitscode/big-event-api:latest